package org.integrallis.drools

global org.apache.log4j.Logger applicationLogger

rule "LoggingWithLog4J"
	when
		object : SomeClass()
	then
	    applicationLogger.info("SomeClass says " + object.getMessage());
		
end

//rule "RinseAndRepeat"
//    //no-loop
//    when
//        object : SomeClass(message == "Hey you!")
//    then
//        applicationLogger.info("Rinse and Repeat");
//        update(object);
//end
 
